---
- name: Load the containers
  hosts: group
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  
#  - name: update cache
#    become: yes
#    apt:
#      update_cache: yes

#  - name: uninstall docker
#    become: yes
#    apt:
#      name: docker-engine
#      state: absent
  - name: ensure repository key is installed
    apt_key:
       id: "58118E89F3A912897C070ADBF76221572C52609D"
       keyserver: "hkp://p80.pool.sks-keyservers.net:80"
       state: present

  - name: ensure docker registry is available
    # For Ubuntu 14.04 LTS, use this repository:
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
    # For Ubuntu 16.04 LTS, use this repo instead:
    # apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-engine update_cache=yes

    # Uncomment the following to enable insecure registries with Docker
    #- name: ensure docker can use insecure registries in 10.11.0.0/16
    #  lineinfile: "dest=/etc/default/docker regexp=^DOCKER_OPTS line=DOCKER_OPTS='--insecure-registry 10.11.0.0/16'"

  - service: name=docker state=restarted

######
  - name: test install docker pip
    apt:
      name: python-pip
      state: present
  
  - pip:
      name: boto
      state: present
  
  - pip:
      name: docker
      state: present

  - service:
      name: docker
      state: started
    become: true

  - pip:
      name: docker-py
      state: present

#######
  - name: Start Jenkins Container
    docker_container:
      image: jenkins
      name: JenkinS 
      ports:
       - "8080:8080"
  - name: Start Sonarqube Container
    docker_container:
      image: sonarqube:6.2
      name: Sonarqube
      state: started
      ports:
       - "9000:9000"
  - name: Start Nexus Container
    docker_container:
      image: sonatype/nexus
      name: Nexus
      state: started
      ports:
       - "8081:8081"
  - name: Start Tomcat Container
    docker_container:
      image: tomcat
      name: Tomcat
      state: started
      ports:
       - "8082:8080"
  - name: Start Jira Container
    docker_container:
      image: cptactionhank/atlassian-jira
      name: Jira
      state: started
      ports:
       - "8083:8080"


